product_name = [
      "JAC 43 Inch Full HD LED TV NGLD, Black - 43JB320",
      "LG, Nanocell TV, 55 inch NANO77R series, WebOS Smart AI ThinQ, Magic Remote, 3 side cinema, HDR10, HLG, AI Sound Pro (5.1.2ch), 2 Pole stand,55NANO776RA.AFU",
      "Xiaomi Redmi Buds 4 Lite Black | 12mm dynamic driver HD Sound Quality IPX4 water-resistant | Advanced Bluetooth 5.2|18.5 Hours Long Battery Life |Google Fast Pair | Glacier Gray, Wireless",
      "Realme 11 Dual-SIM 256GB ROM + 8GB RAM 5G, Glory Black",
      "LG, UHD 4K TV, 55 inch UR78 series, WebOS Smart AI ThinQ, Magic Remote, 3 side cinema, HDR10, HLG, AI Sound (5.1ch), 2 Pole stand, 55UR78006LL.AFU",
      "JAC 55 inch Full HD LED Smart Screen 4K Android TV - 55JB631, VGA, Bluetooth, RF, Ethernet, HDMI",
      "Samsung Galaxy A15 Dual SIM 6GB Ram+128GB ROM (6.5 Inches) (4G LTE) - (Light Blue)",
      "Samsung Galaxy A05 LTE, Android Smartphone, Dual SIM Mobile Phone, 4GB RAM, 64GB Storage, Black",
      "Samsung Galaxy A05 LTE, Android Smartphone, Dual SIM, 6GB RAM, 128GB Storage, Black - 1 year Warranty",
      "Adjustable Laptop Stand, Portable Aluminium Laptop Riser Laptop Holder for Desk, Foldable Ventilated Cooling Computer Support Stand for Apple MacBook Pro/Air, HP, Sony, Dell, More 10-15.6”",
      "Xiaomi Redmi Smart Watch 3 Active Black| 1.83 Inch Big LCD Display, 5ATM Water Resistant, 12 Days Battery Life, GPS, 100+ Workout Mode, Heart Rate Monitor, Full Scale Fitness Tracking",
      "Oraimo FreePods 3C ENC Calling Noise Cancellation, powerful bass 4 mics, Long Playtime True Wireless Earbuds IPX5-Water Resistant, Via App Black",
      "Apple iPad (9th Generation): with A13 Bionic chip, 10.2-inch Retina Display, 64GB, Wi-Fi, 12MP front/8MP Back Camera, Touch ID, All-Day Battery Life – Silver",
      "Nokia t10 android tablet (4g + wi-fi) with 8\" hd display, stereo speakers with ozo playback, 4gb ram + 64gb rom. ocean blue",
      "Samsung Galaxy A15 Dual SIM 8GB Ram+256GGB ROM (6.5 Inches) (4G LTE) - (Black)",
      "LG NanoCell TV 55 Inch NANO84 Series, Cinema Screen Design 4K Active HDR WebOS Smart AI ThinQ Local Dimming - 55NANO846QA",
      "Oraimo Shark 4 Bluetooth Neckband Wireless in Ear Earphones Deep Bass,20Hrs Playtime,ASAP Charge,ENC Tech,Low-Latency Ergonomic Neckband, Sweat-Resistant Magnetic Earbuds, Dual Pairing",
      "Samsung Galaxy A54 - Dual SIM Mobile Phone Android, 8GB RAM, 128GB, 5G, Awesome White - 1 year Warranty",
      "LG UHD 4K TV 55 Inch UQ7500 Series, Cinema Screen Design 4K Active HDR WebOS Smart AI ThinQ - 55UQ75006L, Bluetooth, Wi-Fi, Ethernet, HDMI, NFC",
      "SanDisk Ultra Dual Drive Go USB Type-C 128GB",
      "Realme C53 Dual-SIM 256GB ROM + 8GB RAM 4G (Champion Gold) - Middle East Version",
      "View 43 Inches FHD LED Smart TV, Black - ML43VIEWA620",
      "ROWA 32 Inch HD LED Basic TV, Black",
      "Oraimo Smart watch OSW-16, BrightSilver + 12 Months Local Warranty",
      "Samsung Galaxy A54 Dual SIM 8GB Ram+128GB ROM (6.23 Inches) (5G) - (Awesome Graphite)",
      "Soundcore by Anker P20i Earbuds, 10mm Driver, Bluetooth 5.3, Adjustable EQ, 30H Playtime, IPX5 Waterproof, 2 Microphones with AI, 18 Local Warranty, In-Ear Black Headphones Headset Wireless Earbuds",
      "Samsung Galaxy A54 - Dual SIM Mobile Phone Android, 8GB RAM, 256GB, Awesome Graphite - 1 year Warranty",
      "Samsung Galaxy A54 Dual SIM 8GB Ram+256GB ROM (6.23 Inches) (5G) - (Awesome Lime)",
      "Nokia G21 Dual SIM 4GB Ram+128GB ROM (6.5 Inches) (4G) - (Dusk)",
      "Oraimo Watch Lite 1.69' OSW-18 TFT LCD Display IP68 Waterproof Sports Smart Watch, 12 Months Warranty",
      "Samsung Galaxy A54 - Dual SIM Mobile Phone Android, 8GB RAM, 128GB, 5G, Awesome Lime",
      "Samsung 55 Inch 4K UHD Smart LED TV with Built-in Receiver and Remote Control - Black - UA55CU7000UXEG [2023 Model]",
      "Samsung Galaxy A05s, Android Smartphone, Dual SIM Mobile Phone, LTE, 4GB RAM, 128GB Storage, Black",
      "Itel A58 PRO 2GB RAM+32GB ROM (6.66 Inches) (4G) - (Sky Cyan)",
      "Samsung 32 Inch Full HD Smart LED TV with Built-in Receiver - Black - UA32T5300AUXEG",
      "Soundcore By Anker R50i True Wireless Earbuds 10mm Drivers with Big Bass, Bluetooth 5.3, 30H Playtime, IPX5-Water Resistant, AI Clear Calls with 2 Mics, 22 Preset EQs via App, 18 Months Warranty",
      "Samsung Galaxy A05s, Android Smartphone, Dual SIM Mobile Phone, LTE, 6GB RAM, 128GB Storage, Black",
      "SAMSUNG Galaxy S24 Ultra, AI Android Smartphone, 256GB Storage, 12GB RAM, 200MP Camera, S Pen, Long Battery Life - Titanium Black",
      "Oraimo FreePods Lite True Wireless Earbuds Bluetooth TWS Earphone with APP Control,40h Play Time, Anifast Fast Charging,in-Ear Earbuds with Stereo Bass,Black",
      "Samsung Galaxy Tab A9 LTE Android Tablet, 4GB RAM, 64GB Storage, Silver",
      "Jac 32 inch hd led tv - 32jb310, RF, USB, HDMI",
      "Samsung 50 Inch TV Crystal Processor 4K LED with Built-in Receiver - Black - UA50CU8000UXEG [2023 Model]",
      "OPPO Enco Air2 Pro- Wireless Headphones, Bluetooth 5.2, Noise Cancellation, Fast Charging, Large Capacity Battery, White Headset Wireless Earbuds",
      "Anker USB C Charger, 20W Fast Charger with Foldable Plug, PowerPort III 20W Cube Charger for iPhone 14/14 Plus/14 Pro/14 Pro Max/13, Galaxy, Pixel 4/3, iPad/iPad Mini, and More",
      "Nikai 32 Inches HD Smart LED TV, Black - NE32SLED1",
      "Xiaomi Mi Power Bank 50W 20000mAh, 50W Portable Battery, Bi-Directional Fast Charging, High Power of 74WH, Black",
      "Anker 312 USB-C Charger 25W Supports Samsung Super Fast Charging, MultiProtect Protection, PowerIQ 3.0",
      "Soundcore a3991h11 by anker life p2i true wireless earbuds, ai-enhanced calls, 10mm drivers, 2 eq modes, 28h playtime with fast charging, bluetooth 5.2, lightweight and secure fit, button control"
    ]
    
prices = [
      "9,549",
      "26,999",
      "797",
      "9,999",
      "25,999",
      "15,999",
      "7,299",
      "4,999",
      "5,899",
      "187",
      "2,255",
      "880",
      "17,930",
      "3,999",
      "9,099",
      "23,999",
      "570",
      "15,999",
      "20,999",
      "888",
      "6,999",
      "8,299",
      "4,999",
      "899",
      "15,950",
      "1,099",
      "17,777",
      "17,777",
      "3,999",
      "820",
      "15,910",
      "21,999",
      "5,600",
      "3,725",
      "8,299",
      "6,499",
      "580",
      "7,744",
      "5,699",
      "17,699",
      "1,927",
      "318",
      "5,299",
      "1,699",
      "549",
      "995"
    ],
ratings = [
      "3.3",
      "3.6",
      "3.8",
      "3.8",
      "3.3",
      "3.2",
      "3.8",
      "3.6",
      "3.0",
      "4.0",
      "4.4",
      "3.8",
      "4.8",
      "3.6",
      "4.1",
      "3.6",
      "4.3",
      "4.2",
      "4.3",
      "4.4",
      "3.4",
      "1.7",
      "3.8",
      "3.6",
      "4.0",
      "4.2",
      "4.0",
      "4.1",
      "3.6",
      "4.0",
      "4.2",
      "4.0",
      "4.3",
      "3.5",
      "4.0",
      "4.0",
      "4.1",
      "4.4",
      "4.0",
      "4.1",
      "4.0",
      "3.9",
      "4.2",
      "4.4",
      "3.5",
      "4.3"
    ]
########################
images = [
      "https://m.media-amazon.com/images/I/61TOMogFHmS._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/61IJEBNnu0L._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/51qnTdwpxCL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/31S+HouNZ-L._AC_US40_.jpg",
      "https://m.media-amazon.com/images/I/71VVj2qIIgL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/41Gng1zU8TL._AC_US40_.jpg",
      "https://m.media-amazon.com/images/I/61oWd7JG82L._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/61AfVp7hNHL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/61cl1NEIrdL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/71dYQdmhwFL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/31oDc8zr8ML._AC_US40_.jpg",
      "https://m.media-amazon.com/images/I/31UoVQv6keL._AC_US40_.jpg",
      "https://m.media-amazon.com/images/I/61xn0PNMjIL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/419kmoRUolL._AC_US40_.jpg",
      "https://m.media-amazon.com/images/I/41gbpR5hV6L._AC_US40_.jpg",
      "https://m.media-amazon.com/images/I/81T3mcf46RL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/71TL2Wxej+L._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/31maazfjh-L._AC_US40_.jpg",
      "https://m.media-amazon.com/images/I/61RuDMWoDYL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/31sSlUv8XJL._AC_US40_.jpg",
      "https://m.media-amazon.com/images/I/61PnHlc0HCL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/81Jfh72mtdL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/51onc5akP2L._AC_US40_.jpg",
      "https://m.media-amazon.com/images/I/514nSB8S9pL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/210vE5wPUfL._AC_US40_.jpg",
      "https://m.media-amazon.com/images/I/51VR1mNvIDL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/51hJ81DnBRL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/310ShxnnJ2L._AC_US40_.jpg",
      "https://m.media-amazon.com/images/I/61-YfOhf3uL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/71qOWNxv4jL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/81ZZ+2aDSXL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/41RCXMSxRrL._AC_US40_.jpg",
      "https://m.media-amazon.com/images/I/61C06xysC3L._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/61YAKCk8n2L._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/41Fb-z5QsTL._AC_US40_.jpg",
      "https://m.media-amazon.com/images/I/51o3rh+OuyL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/71xU8w3fHJL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/51ySQH9NhXL._AC_US40_.jpg",
      "https://m.media-amazon.com/images/I/5181ILcyQJL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/21vv6tGm5BL._AC_US40_.jpg",
      "https://m.media-amazon.com/images/I/71xU8w3fHJL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/51kQgMblg9L._AC_US40_.jpg",
      "https://m.media-amazon.com/images/I/716FwKy9FlL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/316ANcQcgxL._AC_US40_.jpg",
      "https://m.media-amazon.com/images/I/71AQ3qEZ-VL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/5180kLXD1tL._AC_UL320_.jpg",
      "https://m.media-amazon.com/images/I/41HmLtVMbeL._AC_US40_.jpg"
      ]

#--------------------------
#--------------------------result

#product_name
# for product in product_name:
#     print(product)


#price
# result_product_name = ""

# for price in prices :
#     for p in price : 
#         print(p)

#ratings
# for rate in ratings :
#     print(rate)

#product_image
for image in images :
    print(image)